name: saans_app
description: A new Flutter project.

publish_to: 'none' 

rticles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.1.1
  firebase_auth: ^1.1.4
  firebase_database: ^6.1.2
  fluttertoast: ^8.0.6
  google_maps_flutter: ^2.0.4
  geolocator: ^7.0.3
  http: ^0.13.3
  flutter_polyline_points: ^1.0.0
  animated_text_kit: ^4.2.1
  provider: ^5.0.0
  font_awesome_flutter: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
 
  uses-material-design: true

  
  assets:
    - images/ambulance.png
    - images/ambulance2.png
    - images/desticon.png
    - images/logo.png
    - images/desticon1.png
    - images/logo1.png
    - images/pickicon.png
    - images/posimarker.png
    - images/redmarker.png
    - images/user_icon.png

  
  fonts:
     - family: Signatra
       fonts:
         - asset: fonts/Signatra.ttf
     - family: Brand-Regular
       fonts:
         - asset: fonts/bolt-regular.ttf
     - family: Brand Bold
       fonts:
         - asset: fonts/bolt-semibold.ttf
